name: GitHub Actions CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy-on-hosting:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    env:
      FIREBASE_PROJECT_ID: coachai-ce493
      FIREBASE_SITE: file-493-da12d
    steps:
      - uses: actions/checkout@v4
      
      - name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}

      - name: Install Firebase Tools
        run: npm install -g firebase-tools

      - name: "Select firebase project"
        run: npx firebase use ${{ env.FIREBASE_PROJECT_ID }}

      - name: "Deploy on Firebase"
        run: npx firebase deploy --only hosting:${{ env.FIREBASE_SITE }}